// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `days_between`, `days_from_epoch`, `travel_days`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 计算差补金额。
Future<double> perDiemAllowance({
  required DateYmd start,
  required DateYmd end,
}) => RustLib.instance.api.crateApiAllowancePerDiemAllowance(
  start: start,
  end: end,
);

/// 仅含年月日的日期，用于跨桥传递（避免引入 chrono 依赖）。
class DateYmd {
  final int year;
  final int month;
  final int day;

  const DateYmd({required this.year, required this.month, required this.day});

  @override
  int get hashCode => year.hashCode ^ month.hashCode ^ day.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DateYmd &&
          runtimeType == other.runtimeType &&
          year == other.year &&
          month == other.month &&
          day == other.day;
}
