// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_title_subtitle`, `category_label`, `detect_category`, `extract_date`, `extract_last_amount`, `extract_route`, `extract_station_route`, `find_all_amount_positions`, `find_all_order_id_positions`, `is_cjk`, `is_currency_char`, `is_valid_amount`, `is_word_char_c`, `parse_ymd_num`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 将 OCR 文本解析为 [OcrParseResult]。
Future<OcrParseResult> parseOcrText({required String text}) =>
    RustLib.instance.api.crateApiOcrParseOcrText(text: text);

/// 从订单列表截图 OCR 文本中抽取全部订单（图片可能含多张订单卡片）。
///
/// 策略：第 N 个订单号 ↔ 第 N 个金额（按出现顺序 1:1 配对）。
/// 这样无论 OCR 输出的金额是：
///   1. 落在每张卡内（按卡阅读），自然与卡内订单号同序；
///   2. 全部统一输出在文末（OCR 未按卡分组），仍按出现顺序与订单号一一对应。
/// 数量不等时按较短者配对，缺失一侧补 None，多余一侧忽略。
/// 无订单号或前缀未知则忽略。
Future<List<ImageHint>> extractAllOrderHints({required String text}) =>
    RustLib.instance.api.crateApiOcrExtractAllOrderHints(text: text);

/// 订单截图抽取结果：订单号前缀即发票类型，末行 ¥xxx 即金额。
class ImageHint {
  /// 订单类型（car/flight/hotel）。
  final String orderType;

  /// 订单号（2 位前缀 + 14~22 位数字，如 DF12345678901234567890）。
  final String orderId;

  /// 末行金额，未识别到为 None。
  final double? amount;

  const ImageHint({
    required this.orderType,
    required this.orderId,
    this.amount,
  });

  @override
  int get hashCode => orderType.hashCode ^ orderId.hashCode ^ amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageHint &&
          runtimeType == other.runtimeType &&
          orderType == other.orderType &&
          orderId == other.orderId &&
          amount == other.amount;
}

/// OCR 解析结果。
class OcrParseResult {
  /// 是否成功解析出可用字段（有金额或类别）。
  final bool ok;

  /// 票据分类名（train/flight/hotel/car），未识别为 None。
  final String? category;

  /// 名称（行程或类别标签），未识别为 None。
  final String? title;

  /// 备注副标题（类别标签 + 日期），未识别为 None。
  final String? subtitle;

  /// 金额，未识别为 None。
  final double? amount;

  const OcrParseResult({
    required this.ok,
    this.category,
    this.title,
    this.subtitle,
    this.amount,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      category.hashCode ^
      title.hashCode ^
      subtitle.hashCode ^
      amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrParseResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          category == other.category &&
          title == other.title &&
          subtitle == other.subtitle &&
          amount == other.amount;
}
