// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failed_result`, `is_valid_category`, `ok_result`, `parse_amount`, `parse_flat_json`, `parse_literal`, `parse_string`, `skip_ws`, `try_parse_etrip`, `try_parse_json`, `try_parse_pipe`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 将扫码内容解析为 [QrParseResult]。
Future<QrParseResult> parseQrContent({required String content}) =>
    RustLib.instance.api.crateApiQrParseQrContent(content: content);

/// 二维码解析结果。
class QrParseResult {
  /// 是否成功解析为明细。
  final bool ok;

  /// 原始扫描内容（无论是否解析成功都会保留）。
  final String raw;

  /// 票据分类名（train/flight/hotel/car），解析失败为 None。
  final String? category;

  /// 名称，解析失败为 None。
  final String? title;

  /// 备注副标题，解析失败为 None。
  final String? subtitle;

  /// 金额，解析失败为 None。
  final double? amount;

  const QrParseResult({
    required this.ok,
    required this.raw,
    this.category,
    this.title,
    this.subtitle,
    this.amount,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      raw.hashCode ^
      category.hashCode ^
      title.hashCode ^
      subtitle.hashCode ^
      amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrParseResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          raw == other.raw &&
          category == other.category &&
          title == other.title &&
          subtitle == other.subtitle &&
          amount == other.amount;
}
